# Generated by Django 3.0.8 on 2020-07-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default='S', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza',
            field=models.CharField(default='Margherita', max_length=30),
            preserve_default=False,
        ),
    ]
